# Generated by Django 2.0.4 on 2018-04-19 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('most_recent_time', models.DateField(default=datetime.datetime(2018, 4, 19, 3, 44, 6, 253929, tzinfo=utc))),
                ('type', models.CharField(max_length=20)),
                ('metric', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('RS_Score', models.FloatField()),
                ('HB_Score', models.FloatField()),
                ('BO_Score', models.FloatField()),
                ('AP_Score', models.FloatField()),
                ('Baseline_Score', models.FloatField()),
                ('RS_Duration', models.IntegerField()),
                ('HB_Duration', models.IntegerField()),
                ('BO_Duration', models.IntegerField()),
                ('AP_Duration', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.DataSet')),
            ],
        ),
    ]
