# Generated by Django 2.0.4 on 2018-04-20 04:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('most_recent_time', models.DateField(default=datetime.datetime(2018, 4, 20, 4, 5, 52, 723413, tzinfo=utc))),
                ('type', models.CharField(max_length=20)),
                ('metric', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('Our_Score', models.FloatField()),
                ('Our_Duration', models.IntegerField()),
                ('Baseline_Score', models.FloatField()),
                ('AutoSklearn_Score', models.FloatField()),
                ('AutoSklearn_Duration', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.DataSet')),
            ],
        ),
    ]
