# Generated by Django 2.0.4 on 2018-04-18 19:05

import backendApp.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('most_recent_time', models.DateField(default=datetime.datetime(2018, 4, 18, 19, 5, 41, 528741, tzinfo=utc))),
                ('type', models.CharField(max_length=20)),
                ('metric', models.CharField(max_length=30)),
                ('train_results', djongo.models.fields.ArrayModelField(default=[], model_container=backendApp.models.Result, model_form_class=backendApp.models.ResultForm)),
            ],
        ),
    ]
