# Generated by Django 2.0.4 on 2018-04-18 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('RS_Score', models.FloatField()),
                ('HB_Score', models.FloatField()),
                ('BO_Score', models.FloatField()),
                ('AP_Score', models.FloatField()),
                ('Baseline_Score', models.FloatField()),
                ('RS_Duration', models.IntegerField()),
                ('HB_Duration', models.IntegerField()),
                ('BO_Duration', models.IntegerField()),
                ('AP_Duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='most_recent_time',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 19, 33, 15, 387315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='train_results',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='backendApp.Result'),
        ),
    ]
