# Generated by Django 2.0.4 on 2018-04-15 01:31

import backendApp.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_auto_20180415_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='metric',
            field=models.CharField(choices=[('R', 'Root_Mean_Squared_Error'), ('F', 'F1_MACRO'), ('M', 'MEAN_SQUARED_ERROR')], default='R', max_length=30),
        ),
        migrations.AddField(
            model_name='dataset',
            name='most_recent_time',
            field=models.DateField(default=datetime.datetime(2018, 4, 15, 1, 31, 58, 999399, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dataset',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dataset',
            name='train_results',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=backendApp.models.Result, model_form_class=backendApp.models.ResultForm),
        ),
        migrations.AddField(
            model_name='dataset',
            name='type',
            field=models.CharField(choices=[('R', 'Regression'), ('C', 'Classification')], default='R', max_length=20),
        ),
    ]
